import re
import subprocess
import sys

def is_ninja_for(cmd):
    return (
        cmd.startswith('for ')
        and '%' in cmd
        and ' do ' not in cmd
        and 'done' not in cmd
    )

def ninja_for_to_bash(cmd):
    m = re.findall(r'^for\s+(\w+)\s+in\s+([^\s;]+);(.+)$', cmd)
    if not m:
        return cmd

    var, pattern, body = m[0]

    pre, post = pattern.split('%', 1)
    glob = pattern.replace('%', '*')

    body = body.replace('%', '${cap}')
    body = body.replace(f'${var}', f'${{{var}}}')

    return (
        f'shopt -s nullglob; '
        f'for {var} in {glob}; do '
        f'cap="${{{var}#{pre}}}"; '
        f'cap="${{cap%{post}}}"; '
        f'echo "{body.strip()}"; '
        f'done'
    )

def expand_bash_commands(template_path):
    with open(template_path) as f:
        lines = f.readlines()

    result = []

    for line in lines:
        stripped = line.lstrip()

        # Skip commented lines
        if stripped.startswith('#'):
            result.append(line)
            continue

        # Find all $(...) expressions
        matches = re.findall(r'\$\(([^()]*)\)', line)

        for raw in matches:
            cmd = raw.strip()

            # Convert only non-bash Ninja for loops
            if is_ninja_for(cmd):
                bash_cmd = ninja_for_to_bash(cmd)
            else:
                bash_cmd = cmd

            try:
                out = subprocess.check_output(
                    ['bash', '-c', bash_cmd],
                    text=True
                ).strip()
            except subprocess.CalledProcessError:
                print(f"[!] Error executing bash command:\n{bash_cmd}")
                sys.exit(1)

            line = line.replace(f'$({raw})', out)

        result.append(line)

    return ''.join(result)


if __name__ == "__main__":
    script_name = sys.argv[0]

    if len(sys.argv) < 2:
        print(f"[!] Usage: python3 {script_name} <template> [output]")
        sys.exit(1)

    input_template = sys.argv[1]
    output_ninja = sys.argv[2] if len(sys.argv) == 3 else "build.ninja"

    try:
        final_content = expand_bash_commands(input_template)

        header = [
            f"# AUTOMATICALLY GENERATED FROM {input_template}",
            f"# Generated by {script_name}\n",
            "rule regen_ninja",
            f"  command = python3 {script_name} {input_template} {output_ninja}",
            "  generator = 1\n",
            f"build {output_ninja}: regen_ninja {input_template} {script_name}\n",
            "#" + "-" * 40 + "\n"
        ]

        with open(output_ninja, "w") as f:
            f.write("\n".join(header))
            f.write(final_content)

        print(f"[*] {output_ninja} successfully generated")

    except Exception as e:
        print(f"[!] Error: {e}")
        sys.exit(1)
